apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: crossplane-nextdns-composition
  annotations:
    meta.crossplane.io/maintainer: jacaudi
    meta.crossplane.io/source: github.com/jacaudi/crossplane-nextdns-composition
    meta.crossplane.io/license: APL-2.0
    meta.crossplane.io/description: |
      A Crossplane configuration that allows you to create and manage NextDNS Profiles.
    meta.crossplane.io/readme: |
      Featuring a Composition with a HTTP Managed Resource that can be used to create a NextDNS Profile.
spec:
  dependsOn:
    - provider: ghcr.io/crossplane-contrib/provider-http
      version: ">=v1.0.10"
      name: provider-http
    - function: xpkg.upbound.io/crossplane-contrib/function-go-templating
      version: ">=v0.4.0"
      name: function-go-templating
    - function: xpkg.upbound.io/crossplane-contrib/function-auto-ready
      version: ">=v0.2.1"
      name: function-auto-ready
  crossplane:
    version: ">=v1.20-0"